#!/bin/sh -e

echo " -- Starting run: `date`"

ROOT=`dirname "$0"`
cd "$ROOT"

source bin/activate

go() {
    echo " - $1"
    [ -f data/current/$1 ] && mv data/current/$1 data/last/$1
    scrapy crawl $1 -o data/current/$1 -t json && \
        [ -f data/last/$1 ] && \
        python compare.py data/last/$1 data/current/$1 "$2"
}

go citybeerstore "@citybeerstore"
go monkskettle "@monkskettle"
