#!/bin/sh -ex

echo " -- Starting run: `date`"

ROOT=`dirname "$0"`
cd "$ROOT"

. bin/activate

go() {
    echo " - $1"
    [ -f data/current/$1 ] && mv data/current/$1 data/last/$1
    if scrapy crawl $1 -o data/current/$1 -t json; then
        if python -mjson.tool data/current/$1 >/dev/null; then
            [ -f data/last/$1 ] && \
            python compare.py data/last/$1 data/current/$1 "$2"
        else
            rm data/current/$1
        fi
    fi
}

go citybeerstore "@citybeerstore"
go monkskettle "@monkskettle"
go 21stamendment "@21stAmendment"
go zeitgeist "Zeitgeist"
