#!/bin/sh -ex

ROOT=`dirname "$0"`

go() {
    mv data/current/$1 data/last/$1
    scrapy crawl $1 -o data/current/$1 -t json
    python compare.py data/last/$1 data/current/$1 "$2"
}

lockfile $ROOT/lock

go citybeerstore "@citybeerstore"

rm -f $ROOT/lock
